//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acconting.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buys
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string Discount { get; set; }
        public string DiscountPrice { get; set; }
        public string Date { get; set; }
        public string Condition { get; set; }
        public int InvoiceNumber { get; set; }
    }
}
