//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acconting.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string PurchasePrice { get; set; }
        public string SalesPrice { get; set; }
        public int Numbers { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string company { get; set; }
    }
}
